### ISSUE TITLE
Directory listing does not refresh

### ISSUE THREAD

**Issue by yoursunny** [zhehaowang/ndnfs-port#1]
Steps to reproduce:
1. start `ndnfs` with an empty filesystem mounted at `/tmp/ndnfs`
2. start `ndnfs-server` at `ndn:/example/ndnfs`
3. `mkdir /tmp/ndnfs/d`
4. access `ndn:/example/ndnfs` in Firefox, "d" shows up
5. `rmdir /tmp/ndnfs/d`
6. refresh `ndn:/example/ndnfs` in Firefox

Expected: "d" disappears (after a few seconds)
Actual: "d" persists

Root cause: NDNFS `_list` Data packet does not set FreshnessPeriod.

From http://named-data.net/doc/ndn-tlv/data.html#freshnessperiod:

> When FreshnessPeriod is omitted, the Data packet cannot be marked stale.

This Data stays in ContentStore indefinitely so Firefox cannot access fresh Data.

**Comment by zhehaowang** [comment]
Thanks Junxiao! Good catch. Updated now.

**Comment by yoursunny** [comment]
Verified that FreshnessPeriod is now set.

Sadly, old Data will stay in the network "forever" until they are evicted, and I had to use `ndn.Exclude` in URIs to avoid them.
