### ISSUE TITLE
Stop using Selectors

### ISSUE THREAD

**Issue by yoursunny** [zhehaowang/ndnfs-port#10]
Interest Selectors are removed in NDN Packet Format v0.3.
NDNFS-server should stop using them.
https://github.com/remap/ndnfs-port/blob/263998c19d40397bb291488b44002fbbe6a776d1/server/servermodule.cc#L155-L158

**Comment by Pesa** [comment]
https://github.com/remap/ndnfs-port/pull/11

**Comment by jefft0** [comment]
Pull request #11 is merged. Closing.
