### ISSUE TITLE
Doesn't work with latest version of NFD (0.5.1), NDN-CPP

### ISSUE THREAD

**Issue by raq154** [zhehaowang/ndnfs-port#9]
Steps to reproduce the issue:
mkdir /tmp/ndnfs
mkdir /tmp/dir
./build/ndnfs /tmp/dir /tmp/ndnfs -o prefix=/ndn/broadcast/ndnfs -o log=ndnfs.log
nohup ./build/ndnfs-server -p /ndn/broadcast/ndnfs -l ndnfs-server.log -f /tmp/ndnfs &

echo "Hello, world!" > /tmp/ndnfs/test.txt
ndnpeek -pf /ndn/broadcast/ndnfs/test

Expected: 
Hello, World

Result: Nothing

logs from ndnfs-server.log:
- 1497342777 DEBUG: onInterest: no such file found in ndnfs: /test
- 1497342777 DEBUG: sendDirMeta: no such folder found: /test

logs from ndnfs.log
- 1497342744 DEBUG: ndnfs_getattr: path=/test.txt
- 1497342744 ERROR: ndnfs_getattr: get_attr failed. Full path /tmp/dir/test.txt. Errno 2
- 1497342744 DEBUG: ndnfs_mknod: path=/test.txt, mode=0100644
- 1497342744 ERROR: mime_infer: found matching mime type for extension: .txt; mime_type: text/plain
- 1497342745 DEBUG: ndnfs_getattr: path=/test.txt
- 1497342745 DEBUG: duplicate_version need to be reimplemented.
- 1497342745 DEBUG: ndnfs_write: path=/test.txt, size=14, offset=0
- 1497342745 DEBUG: ndnfs_release: path=/test.txt, flag=0x8001
- 1497342745 DEBUG: sign_segment: path=/test.txt, ver=1497342745, seg=0, len=14
- 1497342745 DEBUG: sign_segment: segment name is /ndn/broadcast/ndnfs/test.txt/%FDY%3F%A3%19/%00%00
- 1497342777 DEBUG: ndnfs_getattr: path=/test
- 1497342777 ERROR: ndnfs_getattr: get_attr failed. Full path /tmp/dir/test. Errno 2

System Info:
Ubuntu 14.04

Can you share the Ubuntu, NFD & NFD-CPP version where this project works?

**Comment by raq154** [comment]
ndnpeek returns the file if I try to get "/ndn/broadcast/ndnfs/test.txt/%FDY%3F%A3%19/%00%00"

Output:
```
?Xndn   broadcasndnfs
                    test.tx?Y??
Hello, world!
?(?K??
]?\?)?S??R??????2?s?b
?æC?e3
      ?X0;??.u?l?pT?o??s՘4??ukN?=M
                                  ??K~?Å??????
u?Anz?\?\;?d?L?LH,c??V;☹,?u?PgtO???? !?Խḿ?`2q??????:$???B?b???[?Q?L$????z?]
??E?q:??????                                                               ?????]??A14?Y?
            ????F)޽%%ɘ?.ӕ?Q?s?mu???root@3911df6f1914:/ndnfs-port# 

```

**Comment by zhehaowang** [comment]
This doesn't seem to be an NFD version issue; the project was tested with 0.5.1 before.

Any particular reason why you name the file "test.txt", yet send interest for "test" (without .txt) in ndnpeek?

**Comment by raq154** [comment]
Thanks for your prompt response. 
I was getting the same output from "ndnpeek -pf /ndn/broadcast/ndnfs/test.txt" so I tried this command. You can a similar command in the ReadMe file of this repo:

"ndn-tlv-peek -pf /ndn/broadcast/ndnfs/test" 
(ndn-tlv-peek is depreciated now)

Since the project is working fine with NDN-JS so I'm ignoring this issue for now.

**Comment by zhehaowang** [comment]
I see. 
Thanks for pointing this out! 
It is a typo in the readme.
